trigger:
  branches:
    include:
      - main  # or your target branch
  paths:
    include:
      - src/**
      - features/**
      - tests/**
      - package.json
      - tsconfig.json
      - playwright.config.ts

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'test'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install Dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  - script: |
      npm run test:e2e
    displayName: 'Run Cucumber Tests with Playwright'

  - script: |
      npx allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'allure-report'
      artifactName: 'AllureReport'
      publishLocation: 'Container'
    displayName: 'Publish Allure Report Artifact'
