trigger:
- main

jobs:
- job: RunUITests
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies'

  # Run Cucumber with Playwright + TS
  - script: |
      npm run test
    displayName: 'Run Playwright Cucumber Tests'

  # Publish HTML report as pipeline artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: reports
      artifact: 'Cucumber HTML Report'
